Books/Models/Book.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.CompilerServices;

namespace Books.Models
{
    public class Book
    {
        public int Id { get; set; }
        [StringLength(100)]
        [Required]
        public string Title { get; set; }
        [Display(Name = "Published in")]
        [Required]
        public int? YearPublished { get; set; }
        [Display(Name = "Number of pages")]
        [Required]
        public int? NumPages { get; set; }
        [StringLength(int.MaxValue)]
        public string? Description { get; set; }
        [StringLength(50)]
        public string? Publisher { get; set; }
        [StringLength(int.MaxValue)]
        [Display(Name = "Front cover")]
        public string? FrontPage { get; set; }
        [StringLength(int.MaxValue)]
        [Display(Name = "Download link")]
        public string? DownloadUrl { get; set; }
        [Display(Name = "Author")]
        public int AuthorId { get; set; }
        public Author? Author { get; set; }
        public ICollection<BookGenre>? Genres { get; set; }
        public ICollection<Review>? Reviews { get; set; }
        public ICollection<UserBooks>? Users { get; set; }
        [Display(Name = "Average Rating")]
        public float AverageRating()
        {
            if (Reviews != null && Reviews.Any() && Reviews.All(r => r.Rating != null))
            {
                int totalRating = (int)Reviews.Sum(r => r.Rating);
                return (float)totalRating / Reviews.Count;
            }

            return 0;
        }
    }
}

Books/Controllers/AuthorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Books.Data;
using Books.Models;
using Books.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace Books.Controllers
{
    public class AuthorsController : Controller
    {
        private readonly BooksContext _context;

        public AuthorsController(BooksContext context)
        {
            _context = context;
        }

        // GET: Authors
        public async Task<IActionResult> Index(string searchString)
        {
            IQueryable<Author> authors = _context.Author.AsQueryable();

            if (!string.IsNullOrEmpty(searchString))
            {
                authors = authors.Where(a => a.FirstName.Contains(searchString) 
                || a.LastName.Contains(searchString));
            }

            var authorList = await authors.ToListAsync();

            return View(authorList);
        }

        // GET: Authors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = await _context.Author
                .Include(a => a.Books)
                .ThenInclude(b => b.Genres)
                .ThenInclude(b => b.Genre)
                .Include(a => a.Books)
                .ThenInclude(b => b.Reviews)
                .FirstOrDefaultAsync(a => a.Id == id);

            if (author == null)
            {
                return NotFound();
            }

            foreach (var book in author.Books)
            {
                var updatedBook = await _context.Book
                    .Include(b => b.Genres)
                    .ThenInclude(b => b.Genre)
                    .Distinct()
                    .FirstOrDefaultAsync(b => b.Id == book.Id);

                if (updatedBook != null)
                {
                    book.Genres = updatedBook.Genres;
                }
            }

            return View(author);
        }

        // GET: Authors/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Authors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,BirthDate,Nationality,Gender")] Author author)
        {
            if (ModelState.IsValid)
            {
                _context.Add(author);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }

        // GET: Authors/Edit/5
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = _context.Author.Include(a => a.Books).FirstOrDefault(a => a.Id == id);
            if (author == null)
            {
                return NotFound();
            }

            var allBooks = _context.Book.ToList();

            var bookOptions = allBooks.Select(book => new SelectListItem
            {
                Value = book.Id.ToString(),
                Text = book.Title
            }).ToList();

            var selectedBooks = author.Books.Select(book => book.Id).ToList();

            var viewModel = new AuthorViewModel
            {
                Author = author,
                BookOptions = new SelectList(bookOptions, "Value", "Text"),
                SelectedBooks = selectedBooks
            };

            return View(viewModel);
        }

        // POST: Authors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,BirthDate,Nationality,Gender")] Author author)
        {
            if (id != author.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(author);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AuthorExists(author.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }

        // GET: Authors/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = await _context.Author
                .FirstOrDefaultAsync(m => m.Id == id);
            if (author == null)
            {
                return NotFound();
            }

            return View(author);
        }

        // POST: Authors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var author = await _context.Author.FindAsync(id);
            if (author != null)
            {
                _context.Author.Remove(author);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AuthorExists(int id)
        {
            return _context.Author.Any(e => e.Id == id);
        }
    }
}

Books/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Books.Data;
using Books.Models;
using Books.ViewModels;
using System.ComponentModel.Design;
using Microsoft.AspNetCore.Authorization;

namespace Books.Controllers
{
    public class BooksController : Controller
    {
        private readonly BooksContext _context;

        public BooksController(BooksContext context)
        {
            _context = context;
        }

        // GET: Books
        public async Task<IActionResult> Index(string searchString)
        {
            IQueryable<Book> books = _context.Book.Include(b => b.Author).Include(b => b.Genres).ThenInclude(bg => bg.Genre).Include(b => b.Reviews);
            IQueryable<string> titleQuery = _context.Book.OrderBy(b => b.Title).Select(b => b.Title).Distinct();

            if (!string.IsNullOrEmpty(searchString))
            {
                books = books.Where(b => 
                b.Title.Contains(searchString) || 
                b.Author.FirstName.Contains(searchString) ||
                b.Author.LastName.Contains(searchString) ||
                b.Genres.Any(b => b.Genre.GenreName.Contains(searchString)
                ));
            }

            foreach (var book in books)
            {
                var distinctGenres = book.Genres
                    .Where(bg => bg.Genre != null)
                    .GroupBy(bg => bg.GenreId)
                    .Select(group => group.First())
                    .ToList();

                book.Genres = distinctGenres;
            }

            var bookVM = new BookFilterViewModel
            {
                TemporaryBooks = await books.ToListAsync(),
                FilterOptions = new SelectList(await titleQuery.ToListAsync())
            };

            return View(bookVM);
        }

        [Authorize(Roles = "User")]
        public async Task<IActionResult> Buy(int id)
        {
            var userId = User.Identity.Name; // Assuming the user name is unique
            var userBook = new UserBooks
            {
                AppUser = userId,
                BookId = id
            };

            _context.UserBooks.Add(userBook);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }


        // GET: Books/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Book
                .Include(b => b.Author)
                .Include(b => b.Genres)
                .ThenInclude(b => b.Genre)
                .Distinct()
                .Include(b => b.Reviews)
                .FirstOrDefaultAsync(b => b.Id == id);

            if (book == null)
            {
                return NotFound();
            }
            
            return View(book);
        }

        // GET: Books/Create
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create()
        {
            ViewBag.Genres = new MultiSelectList(await _context.Genre.ToListAsync(), "Id", "GenreName");
            ViewBag.AuthorId = new SelectList(await _context.Author.ToListAsync(), "Id", "FullName");
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("Id,Title,YearPublished,NumPages,Description,Publisher,FrontPage,DownloadUrl,AuthorId")] Book book, int[] selectedGenres)
        {
            if (ModelState.IsValid)
            {
                _context.Add(book);
                await _context.SaveChangesAsync();

                if (selectedGenres != null)
                {
                    foreach (var genreId in selectedGenres)
                    {
                        _context.Add(new BookGenre { BookId = book.Id, GenreId = genreId });
                    }
                    await _context.SaveChangesAsync(); 
                }

                return RedirectToAction(nameof(Index));
            }
            ViewBag.AuthorId = new SelectList(await _context.Author.ToListAsync(), "Id", "FullName", book.AuthorId);
            ViewBag.Genres = new MultiSelectList(await _context.Genre.ToListAsync(), "Id", "GenreName", selectedGenres);
            return View(book);
        }

        // GET: Books/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Book
                .Include(b => b.Genres)
                .FirstOrDefaultAsync(b => b.Id == id);

            if (book == null)
            {
                return NotFound();
            }

            var selectedGenreIds = book.Genres.Select(bg => bg.GenreId).ToList();
            
            ViewBag.AuthorId = new SelectList(await _context.Author.ToListAsync(), "Id", "FullName", book.AuthorId);
            ViewBag.Genres = new SelectList(await _context.Genre.ToListAsync(), "Id", "GenreName", book.Genres.Select(bg => bg.GenreId));
            ViewBag.SelectedGenres = selectedGenreIds;
            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,YearPublished,NumPages,Description,Publisher,FrontPage,DownloadUrl,AuthorId")] Book book, int[] selectedGenres)
        {
            if (id != book.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(book);

                    var existingGenres = _context.BookGenre.Where(bg => bg.BookId == id);
                    _context.BookGenre.RemoveRange(existingGenres);

                    if (selectedGenres != null)
                    {
                        foreach (var genreId in selectedGenres)
                        {
                            _context.Add(new BookGenre { BookId = book.Id, GenreId = genreId });
                        }
                    }

                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookExists(book.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            ViewBag.Genres = new MultiSelectList(await _context.Genre.ToListAsync(), "Id", "GenreName", selectedGenres);
            ViewBag.AuthorId = new SelectList(_context.Author, "Id", "FullName", book.AuthorId);
            return View(book);
        }

        // GET: Books/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Book
                .Include(b => b.Author)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var book = await _context.Book.FindAsync(id);
            if (book != null)
            {
                _context.Book.Remove(book);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookExists(int id)
        {
            return _context.Book.Any(e => e.Id == id);
        }
    }
}

Books/Views/Books/Create.cshtml
@model Books.Models.Book

@{
    ViewData["Title"] = "Create";
}

<h1>Add a new book</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="YearPublished" class="control-label"></label>
                <input asp-for="YearPublished" class="form-control" />
                <span asp-validation-for="YearPublished" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumPages" class="control-label"></label>
                <input asp-for="NumPages" class="form-control" />
                <span asp-validation-for="NumPages" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Publisher" class="control-label"></label>
                <input asp-for="Publisher" class="form-control" />
                <span asp-validation-for="Publisher" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FrontPage" class="control-label">Cover Image URL: </label>
                <input asp-for="FrontPage" class="form-control" />
                <span asp-validation-for="FrontPage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DownloadUrl" class="control-label"></label>
                <input asp-for="DownloadUrl" class="form-control" />
                <span asp-validation-for="DownloadUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AuthorId" class="control-label"></label>
                <select asp-for="AuthorId" class ="form-control" asp-items="ViewBag.AuthorId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Genres">Genres: </label>
                <div>
                    @foreach (var genre in ViewBag.Genres)
                    {
                        <div class="form-check">
                            @{
                                int genreId = (int.Parse(genre.Value));
                                bool isChecked = (ViewBag.SelectedGenres as List<int>)?.Contains(genreId) ?? false;
                            }
                            <input type="checkbox" class="form-check-input" name="selectedGenres" value="@genre.Value" id="@genre.Value" 
                            @(isChecked ? "checked" : "")/> @genre.Text
                        </div>
                    }
                </div>
            </div>
            <input type="submit" value="Create" class="btn btn-primary" />
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Books/Views/Books/Delete.cshtml
@model Books.Models.Book

@{
    ViewData["Title"] = "Delete";
}

<h3>Are you sure you want to delete @Model.Title?</h3>
<div>
    <h4>Book</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.YearPublished)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.YearPublished)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumPages)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumPages)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Publisher)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Publisher)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FrontPage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FrontPage)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DownloadUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DownloadUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Books/Views/Books/Details.cshtml
@model Books.Models.Book

@{
    ViewData["Title"] = $"Details - {Model.Title}";
}

<div class="container mt-4">
    <div class="row d-flex align-items-start">
        <div class="col-md-4">
            @if (!string.IsNullOrEmpty(Model.FrontPage))
            {
                <img src="@Model.FrontPage" class="img-fluid rounded shadow"
                     style="max-width: 100%; max-height: 100vh; object-fit: contain;" alt="@Model.Title cover" />
            }
            else
            {
                <p class="text-muted">No cover image available.</p>
            }
        </div>

        <div class="col-md-8 d-flex flex-column">
            <h1 class="display-4">@Model.Title</h1>
            <p class="lead">
                by <strong><a asp-action="Details" asp-controller="Authors" asp-route-id="@Model.Author.Id">@Model.Author.FullName</a></strong>
            </p>

            <dl class="row mt-4">
                <dt class="col-sm-4">Year Published</dt>
                <dd class="col-sm-8">@Html.DisplayFor(model => model.YearPublished)</dd>

                <dt class="col-sm-4">Genres</dt>
                <dd class="col-sm-8">
                    @if (Model.Genres == null || !Model.Genres.Any())
                    {
                        <span class="badge bg-warning text-dark">No genres available</span>
                    }
                    else
                    {
                        @foreach (var genre in Model.Genres)
                        {
                            <a asp-action="Details" asp-controller="Genres" asp-route-id="@genre.GenreId" class="badge bg-secondary">@genre.Genre.GenreName</a>
                        }
                    }
                </dd>

                <dt class="col-sm-4">Publisher</dt>
                <dd class="col-sm-8">@Html.DisplayFor(model => model.Publisher)</dd>

                <dt class="col-sm-4">Number of Pages</dt>
                <dd class="col-sm-8">@Html.DisplayFor(model => model.NumPages)</dd>

                <dt class="col-sm-4">Average Rating</dt>
                <dd class="col-sm-8">
                    <span class="badge bg-info text-dark">@Model.AverageRating() / 10</span>
                </dd>

                <dt class="col-sm-4">Description</dt>
                <dd class="col-sm-8">
                    <p>@Html.DisplayFor(model => model.Description)</p>
                </dd>

                @if (User.Identity.IsAuthenticated && User.IsInRole("User"))
                {
                    <dt class="col-sm-4">Download</dt>
                    <dd class="col-sm-8">
                        <a href="@Model.DownloadUrl" class="btn btn-outline-success" target="_blank">
                            <i class="bi bi-download"></i> Download Book
                        </a>
                    </dd>
                }
            </dl>
        </div>
    </div>

    <hr class="my-4" />

    <div>
        <h2>Reviews for <span class="text-primary">@Model.Title</span></h2>
        @if (Model.Reviews == null || !Model.Reviews.Any())
        {
            <p class="text-muted">No reviews available for this book.</p>
        }
        else
        {
            <ul class="list-group">
                @foreach (var review in Model.Reviews)
                {
                    <li class="list-group-item d-flex justify-content-between align-items-start">
                        <div class="ms-2 me-auto">
                            <div class="fw-bold">@review.AppUser</div>
                            <span>@review.Comment</span>
                        </div>
                        <span class="badge bg-primary rounded-pill">Rating: @review.Rating / 10</span>
                    </li>
                }
            </ul>
        }
    </div>

    <div class="mt-4">
        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
        {
            <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-warning">Edit Book</a>
        }
        <a asp-action="Index" class="btn btn-secondary">Back to List</a>
    </div>
</div>

Books/Views/Books/Index.cshtml
@model Books.ViewModels.BookFilterViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>Overview of our book collection</h1>

@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <p>
        <a asp-action="Create" class="btn btn-success">Add new book</a>
    </p>
}

<form asp-controller="Books" asp-action="Index" method="get">
    <div class="row mb-3">
        <div class="col-md-8">
            <input type="text" asp-for="SearchString" class="form-control" placeholder="Search by author, title, or genre..." />
        </div>
        <div class="col-md-4">
            <input type="submit" value="Filter" class="btn btn-primary" />
        </div>
    </div>
</form>

<div class="row">
    @if (Model.TemporaryBooks != null)
    {
        @foreach (var item in Model.TemporaryBooks)
        {
            <div class="col-md-4 mb-4">
                <div class="card">
                    <div class="card-body">
                        @if (!string.IsNullOrEmpty(item.FrontPage))
                        {
                            <img src="@item.FrontPage" alt="Book Cover" class="card-img-top img-fluid" style="height: 300px; object-fit: cover;" />
                        }
                        else
                        {
                            <p>No cover image available.</p>
                        }
                        <h5 class="card-title mt-3">@item.Title</h5>
                        <p class="card-text">
                            <strong>Author:</strong> <a asp-action="Details" asp-controller="Authors" asp-route-id="@item.Author.Id">@item.Author.FullName</a><br />
                            <strong>Published:</strong> @item.YearPublished<br />
                            <strong>Genres:</strong>
                            @if (item.Genres != null && item.Genres.Any())
                            {
                                <ul>
                                    @foreach (var genre in item.Genres)
                                    {
                                        <li><a asp-action="Details" asp-controller="Genres" asp-route-id="@genre.GenreId">@genre.Genre.GenreName</a></li>
                                    }
                                </ul>
                            }
                            else
                            {
                                <span>No genres associated with @item.Title.</span>
                            }
                        </p>
                        <p><strong>Average Rating:</strong> @item.AverageRating()</p>
                        <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-info">Details</a>
                        @if (User.Identity.IsAuthenticated && User.IsInRole("User"))
                        {
                            <a asp-action="Buy" asp-route-id="@item.Id" class="btn btn-primary">Add</a>
                        }
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning">Edit</a>
                            <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a>
                        }
                    </div>
                </div>
            </div>
        }
    }
</div>